-- 기본키(PRIMARY KEY : PK) = NULL 불가, 테이블 내 중복 값 불가

-- 회원 정보 테이블
CREATE TABLE BOARD_MEMBER(
	-- 컬럼명 자료형 [제약조건]
	MEMBER_ID VARCHAR(20) PRIMARY KEY
	, MEMBER_PW VARCHAR(20) NOT NULL
	,  MEMBER_NAME VARCHAR(20) NOT NULL
	, GENDER VARCHAR(2) -- '남','여'
	, MEMBER_EMAIL VARCHAR(30) NOT NULL UNIQUE
	, IS_ADMIN VARCHAR(2) DEFAULT 'N' -- 'N : 일반회원','Y : 관리자'
);
INSERT INTO board_member (MEMBER_ID,

-- 게시글 정보 테이블
-- WRITER : 외래키(Foreign key : FK) 제약조건
CREATE TABLE BOARD(
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, TITLE VARCHAR(30) NOT NULL
	, CONTENT VARCHAR(30)
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, READ_CNT INT DEFAULT 0
);
-- 게시글 전체 갯수 조회
SELECT COUNT(BOARD_NUM) FROM board;
-- 게시글 갯수대로 자르기
-- (LIMIT : ~개만큼 출력 / OFFSET : 앞의 값 ~개 건너뛰고 출력)
SELECT BOARD_NUM
FROM board
ORDER BY BOARD_NUM
LIMIT 5 OFFSET 5;

CREATE TABLE BOARD_REPLY(
	REPLY_NUM INT AUTO_INCREMENT PRIMARY KEY
	, CONTENT VARCHAR(50) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, BOARD_NUM INT REFERENCES board (BOARD_NUM)
);

INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES ('AA', 'BB', NULL);

SELECT * FROM BOARD;
SELECT * FROM board_member;
SELECT * FROM board_reply;
UPDATE board_member SET IS_ADMIN = 'Y' WHERE MEMBER_ID = 'sydl13';
COMMIT;

SELECT NOW();
