-- 기본 게시판 테이블
CREATE TABLE BASIC_BOARD (
	BOARD_NUM INT PRIMARY KEY -- NOT NULL, 중복 X
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(50)
	, WRITER VARCHAR(20) NOT NULL
	, CREATE_DATE VARCHAR(20) NOT NULL -- 2023-01-10
	, READ_CNT INT DEFAULT 0 -- 조회수


);

SELECT * FROM basic_board;