CREATE TABLE CAR_INFO (
   CAR_NUM INT AUTO_INCREMENT PRIMARY KEY
   , CAR_NAME VARCHAR(20) NOT NULL
   , CAR_PRICE INT DEFAULT 0 NOT NULL
   , CAR_COMPANY VARCHAR(10) NOT NULL
);
DROP TABLE car_info;
DROP TABLE sales_info;

CREATE TABLE SALES_INFO (
   SALES_NUM INT AUTO_INCREMENT PRIMARY KEY
   , SALES_NAME VARCHAR(20) NOT NULL
   , SALES_TEL VARCHAR(20)
   , SALES_COLOR VARCHAR(20) NOT NULL
   , SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
   , CAR_NUM INT NOT NULL REFERENCES CAR_INFO (CAR_NUM)
);