-- 학급 정보
CREATE TABLE CLASS_INFO(
	CLASS_CODE INT AUTO_INCREMENT PRIMARY KEY
	, CLASS_NAME VARCHAR(20) NOT NULL
);

INSERT INTO CLASS_INFO VALUES(1, '자바반');
INSERT INTO CLASS_INFO VALUES(2, '디자인반');
INSERT INTO CLASS_INFO VALUES(3, '캐드반');

SELECT * FROM class_info;

-- 학생 정보
CREATE TABLE  STUDENT_INFO(
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(20) NOT NULL
	, CLASS_CODE INT REFERENCES class_info (CLASS_CODE)
);

SELECT * FROM STUDENT_INFO;

-- 학생 점수 정보
CREATE TABLE STU_SCORE(
	SCORE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, KOR_SCORE INT DEFAULT 0
	, ENG_SCORE INT DEFAULT 0
	, MATH_SCORE INT DEFAULT 0
	, STU_NUM INT REFERENCES STUDENT_INFO (STU_NUM)
);

SELECT * FROM stu_score;
DELETE FROM stu_score WHERE SCORE_NUM=16;

DROP TABLE stu_score;

SELECT * FROM stu_score [WHERE STU_NUM = 2];

INSERT INTO STU_SCORE VALUES(1, 100, 100, 100, 1);

INSERT INTO STUDENT_INFO VALUES (1,'김자바', 1);
INSERT INTO STUDENT_INFO VALUES (2,'이자바', 1);
INSERT INTO STUDENT_INFO VALUES (3,'박자바', 1);
INSERT INTO STUDENT_INFO VALUES (4,'최자바', 1);
INSERT INTO STUDENT_INFO VALUES (5,'정자바', 1);

INSERT INTO STUDENT_INFO VALUES (6,'김디자인', 2);
INSERT INTO STUDENT_INFO VALUES (7,'이디자인', 2);
INSERT INTO STUDENT_INFO VALUES (8,'박디자인', 2);
INSERT INTO STUDENT_INFO VALUES (9,'최디자인', 2);
INSERT INTO STUDENT_INFO VALUES (10,'정디자인', 2);

INSERT INTO STUDENT_INFO VALUES (11,'김캐드', 3);
INSERT INTO STUDENT_INFO VALUES (12,'이캐드', 3);
INSERT INTO STUDENT_INFO VALUES (13,'박캐드', 3);
INSERT INTO STUDENT_INFO VALUES (14,'최캐드', 3);
INSERT INTO STUDENT_INFO VALUES (15,'정캐드', 3);
COMMIT;

SELECT * FROM student_info;

SELECT * FROM board;
SELECT * FROM board_member;

-- 모든 게시글 번호, 제목, 작성자명, 작성자 아이디 조회
SELECT BOARD_NUM, TITLE, MEMBER_NAME, MEMBER_ID
FROM board INNER JOIN board_member
ON WRITER = MEMBER_ID;

-- 모든 학생의 학번, 반이름, 학생명 조회
SELECT STU_NUM, CLASS_NAME, STU_NAME
FROM class_info C INNER JOIN student_info S
ON C.CLASS_CODE = S.CLASS_CODE;




-- 세개 연결

SELECT
   S.STU_NUM
   , CLASS_NAME
   , STU_NAME
   , KOR_SCORE
   , ENG_SCORE
   , MATH_SCORE
FROM STU_SCORE SS INNER JOIN STUDENT_INFO S
ON SS.STU_NUM = S.STU_NUM
INNER JOIN class_info C
ON S.CLASS_CODE = C.CLASS_CODE
WHERE S.STU_NUM = 2;


        
 SELECT
        S.STU_NUM
        , CLASS_NAME
        , STU_NAME
        , KOR_SCORE
        , ENG_SCORE
        , MATH_SCORE
        FROM STU_SCORE SS
        -- RIGHT OUTER : 후에 나온 테이블의 교집합 바깥까지 조회
        RIGHT OUTER JOIN STUDENT_INFO S
        ON SS.STU_NUM = S.STU_NUM
		  INNER JOIN class_info C
        ON S.CLASS_CODE = C.CLASS_CODE       
        WHERE S.STU_NUM = 1;
        
        