-- 학생관리 프로그램 테이블
CREATE TABLE STU (
	STU_NO INT PRIMARY KEY
	, STU_NAME VARCHAR(10) NOT NULL
	, KOR_SCORE INT DEFAULT 0
	, ENG_SCORE INT DEFAULT 0
	, INTRO VARCHAR(50)
);

SELECT * FROM stu;

studentCOMMIT;